# Generated by Django 5.0.4 on 2024-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT_COLLABORATION_SPECIALIST', 'Chuyên viên cộng tác sinh viên'), ('STUDENT_ASSISTANT', 'Trợ lý sinh viên'), ('STUDENT', 'Sinh viên'), ('ADMIN', 'Administrator')], default='Sinh viên', max_length=50),
        ),
    ]
