# Generated by Django 5.0.4 on 2024-05-05 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deficiencyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficiency_reports', to='users.student'),
        ),
        migrations.AddField(
            model_name='participation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='participation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='list_of_participants',
            field=models.ManyToManyField(related_name='activities', through='activities.Participation', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='deficiencyreport',
            unique_together={('student', 'activity')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('student', 'activity')},
        ),
    ]
