# Generated by Django 5.0.4 on 2024-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0002_initial'),
        ('users', '0003_remove_student_student_id_student_student_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by_type', 'created_by_id'], name='activities__created_8d6a54_idx'),
        ),
    ]
