# Generated by Django 5.0.4 on 2024-05-05 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterofstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='students',
            field=models.ManyToManyField(related_name='semesters', through='schools.SemesterOfStudent', to='users.student'),
        ),
        migrations.AddField(
            model_name='trainingpoint',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='schools.criterion'),
        ),
        migrations.AddField(
            model_name='trainingpoint',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='schools.semester'),
        ),
        migrations.AddField(
            model_name='trainingpoint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='semesterofstudent',
            unique_together={('semester', 'student')},
        ),
    ]
